- hosts: "{{groups['db'][0]}}"
  become: yes

  tasks:

    - name: install plugin
      shell: docker plugin install --grant-all-permissions vieux/sshfs

    - name: Create Volume
      shell: docker volume create --driver vieux/sshfs \
            -o sshcmd=test@node2:/home/test \
            -o password=testpassword \
            sshvolume

    #- name: Cria Servico MySQL
    #  docker_swarm_service:
    #    name: MySQL
    #    image: mysql
    #    mode: replicated
    #    replicas: 2
    #    env:
    #      MYSQL_DATABASE: db_mediawiki
    #      MYSQL_USER: mediawiki
    #      MYSQL_PASSWORD: '123456'
    #      MYSQL_ROOT_PASSWORD: '123456'
    #    publish:
    #     - published_port: 3306
    #     - target_port: 3306
    #    mounts:
    #     - source: mysql
    #     - target: /var/lib/mysql
    #     - type: bind
    #     - propagation: rshared
    #    placement:
    #      preferences:
    #        - spread: node.labels.db