---
##########################################################
#                                                        #
#      Playbook - Instalação do docker_container         #
#                                                        #
##########################################################
- hosts: swarmnode
  gather_facts: yes
  become: yes
  vars:
   Caminho: /mnt/r/Uol/Config/
   Token: Token.Worker
   file: "{{Caminho}}{{ Token }}"
   Master: "{{groups['swarmmaster'][0]}}"


  tasks:

  - name: Valida se a pasta existe
    stat:
      path: "{{Caminho}}"
    register: valida

  - name: Criando a pasta
    file:
     path: "{{Caminho}}"
     state: directory
    when: valida.stat.exists == false

  - name: Captura o arquivo Token                                                                                                                         
    copy:
      src: "{{Caminho}}{{ Token }}"
      dest: "{{Caminho}}{{ Token }}"
 
  - name: Captura o arquivo de IP-Host                                                                                                                       
    copy:
      src: "{{Caminho}}IPS/"
      dest: "{{Caminho}}IPS/IP-{{Master}}"      

  - name: read file token
    set_fact:
      v_Token: "{{ lookup('file','{{Caminho}}{{ Token }}')}}"
  - name: file
    set_fact:
      v_Master: "{{ lookup('file','{{Caminho}}IPS/IP-{{Master}}')}}:2377"
  - name: file
    set_fact:
      v_Ip: "{{ lookup('file','{{Caminho}}IPS/IP-{{ansible_hostname}}')}}"

  - name: Add nodes
    docker_swarm:
     state: join
     advertise_addr: "{{v_Ip}}"
     join_token: "{{v_Token}}"
     remote_addrs: [ "{{v_Master}}" ]

#- hosts: swarmmaster
#  become: yes
#
#  tasks:
#    - name: Promote Node
#      shell: docker node promote "{{item}}"
#      loop:
#        - "{{groups['swarmnode'][0]}}"
#        - "{{groups['db'][0]}}"
#        - "{{groups['db'][1]}}"
#
#    - name: Tag - db
#      shell: docker node update --label-add db "{{item}}"
#      loop:
#        - "{{groups['db'][0]}}"
#        - "{{groups['db'][1]}}"
#
#    - name: Tag - app
#      shell: docker node update --label-add app "{{item}}"
#      loop:
#        - "{{groups['APP'][0]}}"
#        - "{{groups['APP'][1]}}"
#